### ISSUE TITLE
Whether the post-processing dataset will be open source？

### ISSUE THREAD

**Issue by NextNode66** [UkcheolShin/TsfmLearner#1]

**Comment by UkcheolShin** [comment]
Yes, you can find the original dataset (rosbag format dataset) here [official website](https://sites.google.com/view/dgbicra2019-vivid/).
Also, you can download the processed dataset via a download link after filling out a simple [survey](https://docs.google.com/forms/d/e/1FAIpQLSd2IndM_BvsBQ2NypmoF8hGNdVFLQcdHifbHFYAgl62K_z-Pw/viewform?usp=pp_url).
Thank you.
