### ISSUE TITLE
About time synchronization

### ISSUE THREAD

**Issue by Junyu-Z** [UkcheolShin/TsfmLearner#2]
Multi-Spectral Consistency Loss is base on the premise that RGB images and Thermal images are synchronized. But I found that there is a delay in the ViViD++ dataset. So I wonder you how to handle this problem when post-processing this dataset?

**Comment by UkcheolShin** [comment]
The provided post-processed dataset is based on ViViD dataset, it is a handhelded multi-sensor dataset. 
And ViViD++ dataset is the recently released outdoor driving dataset.
I think what you mean is the ViViD dataset.

Where you can find a delay between RGB and thermal image stream?
In a ROSbag? There were lots of issues when I made the post-processed dataset. 
So I frequently contact the author of ViViD dataset and ask for time offsets, some specifications, and etc. 
I am not sure current version of the original ViViD raw dataset is modified or not.
